### ISSUE TITLE
Questions about dataset "An EEG dataset recorded during affective music listening"

### ISSUE THREAD

**Issue by qiqing-li** [brainhack-school2020/Biosignal-Emotions-BHS-2020#18]
Hi! Your project looks awesome, and I'd like to ask a question about the dataset "An EEG dataset recorded during affective music listening" as I saw in your readme that you used the dataset:). I'm working on a music project using the dataset but failed to identify which specific song they gave to each participant. I saw in the json files like "sub-**_task-runx_events.json" that they have

```
	"301-360":
	{
		"LongName":	"Music stimuli",
		"Description": "The piece of music that was played. To identify which .mp3 file was played to the participants subtract 300 from this code and append .mp3, for example for code '305' the file '005.mp3' was played to the participant. The corresponding mp3 files can be downloaded from https://www.jyu.fi/hytk/fi/laitokset/mutku/en/research/projects2/past-projects/coe/materials/emotion/soundtracks/Index"
	},
```
and I downloaded the soundtrack files from the link, but I'm still having trouble determining which soundtrack they used for each subject. Will really appreciate it if you figured this out in your project or if you have any advice on this. Thank you!

**Comment by danibene** [comment]
Hi, thanks! 

We didn't use this information in our project, so unfortunately we don't have any advice for you. Best of luck with your project :)

**Comment by qiqing-li** [comment]
> Hi, thanks!
> 
> We didn't use this information in our project, so unfortunately we don't have any advice for you. Best of luck with your project :)

Thanks still! I'll try to reach out to the authors for more information!
