### ISSUE TITLE
Predicting Tags

### ISSUE THREAD

**Issue by Alex-A14** [brainhack-school2020/Biosignal-Emotions-BHS-2020#3]
This is cool!
I took a quick look at the HCI page. What kind of tags would you be looking to predict? Something binary (e.g. distracting/not distracting, accurate/inaccurate), or a range of more descriptive tags?

Do you know what intervals you would use for EEG? i.e. Are you looking at the signal near a particular event or across stimulus exposure?

**Comment by danibene** [comment]
Thanks! We were thinking of predicting valence and arousal (for the datasets where this is available). Do you already know what you'll be predicting for your project (e.g. which piece was played)?

As for the EEG, it's a difficult question, especially when the stimuli durations are different! We thought we'd look at the signal across stimulus exposure, or e.g. the first X seconds when they're different lengths.

**Comment by danibene** [comment]
Update: we ended up not predicting valence and arousal and rather predicting "target emotions". Thank you for bringing up this issue, it wasn't straightforward!
