### ISSUE TITLE
Which features will be used

### ISSUE THREAD

**Issue by ltetrel** [brainhack-school2020/Biosignal-Emotions-BHS-2020#6]
Hi @danibene and @kabbabi,

Congrats for this clear project description, this looks promising!

I was wondering what kind of features from ECG and other biosignals you would like to extract and analyse ? For ex : the frequency spectrum, time-frequency image, wavelet transform etc..

**Comment by kabbabi** [comment]
Hi @ltetrel thank you for your message,

Here are the features we a priori think we will use :
From ECG : RR intervals and Heart Rate Variability, Cepstral analysis, Autocorrelation matrix
From EEG : Spectral analysis (Power Spectrum Density, Phase), Cepstral analysis, Autocorrelation matrix, Cross-correlation between channels,  Singular spectrum analysis, Time-Frequency analysis, Wavelet Transform, Multiresolution analysis

We think we would use ECG data first to denoise EEG from cardiac artifacts, and then also to see if there are any correlations between features extracted from ECG and EEG.

Will there be any tutorials about these features ?
Best,
Achraf

**Comment by ltetrel** [comment]
Humm, I am sure nilearn has some
