### ISSUE TITLE
creating common repositories

### ISSUE THREAD

**Issue by guenounz** [brainhack-school2020/Biosignal-Emotions-BHS-2020#7]
hi ! bit of a technical question, apologies in advance, but how did you create a repository for your team ? i've been having trouble with it, cloning/importing didn't seem to work :(

**Comment by danibene** [comment]
Hi, good question! We had the same problem and @SamGuay helped us.

**Comment by SamGuay** [comment]
I followed with @guenounz. Thanks for tagging me!
