### ISSUE TITLE
This is an interesting project; I am wondering that are you planning to merge all the mentioned data sets to extract your desired features or you will use just one of them?

### ISSUE THREAD

**Issue by srastegarnia** [brainhack-school2020/Biosignal-Emotions-BHS-2020#8]

**Comment by danibene** [comment]
Thanks for your question! While I think it would be really interesting to see whether we could build a classifier that could generalize to multiple data sets, that's beyond the scope of what we expect to accomplish during the next few weeks - so we'll probably just use one of them.
