### ISSUE TITLE
Making the repository private ?

### ISSUE THREAD

**Issue by kabbabi** [brainhack-school2020/Biosignal-Emotions-BHS-2020#9]
Hello,

My collegue Danielle (@danibene) and myself (@kabbabi) want to make the Biosignal-Emotions-BHS-2020 repository private.
GitHub indicates that's an action in the "Danger Zone" ... Does it mean you BHS2020 organizers won't be able to access the folder ?

Thanks,
Achraf

**Comment by danibene** [comment]
It seems we were able to delete the CSV files we wanted to be private with ```git filter-branch --force --index-filter "git rm --cached --ignore-unmatch *.csv" --prune-empty --tag-name-filter cat -- --all``` and ```git push -f``` 

Assuming that we didn't accidentally break anything, I'm closing this for now.
